### PR TITLE
Fix SIGWINCH definition on BSDs

### PR DESCRIPTION
**Pull request by wooosh**

### CODE REVIEW

**Comment by willeccles** [comment]
Builds on macOS, looks good to me.

**Comment by swindlesmccoop** [comment]
How do I define that I'm using OpenBSD? If it's supposed to automatically recognize it, it's not on my machine. I see nothing in the Makefile or config.h about it either.

**Comment by sophec** [comment]
> How do I define that I'm using OpenBSD? If it's supposed to automatically recognize it, it's not on my machine. I see nothing in the Makefile or config.h about it either.

Looks like the compiler should be defining `__OpenBSD__`. Is this not the case? What issue are you having? cfm does not need to know what OS you are using, really. It should just work.

**Comment by swindlesmccoop** [comment]
I can compile the program just fine using GCC, yet using `make` to do it causes it to produce the error. All I'm running is `make` and it produces this:
```
cc -O2 -pipe  -O3 -s -std=c11 -Wall -W -pedantic  -D_XOPEN_SOURCE=700  cfm.c -o cfm
cfm.c:1353:19: error: use of undeclared identifier 'SIGWINCH'
    if (sigaction(SIGWINCH, &sa_resize, NULL) < 0) {
                  ^
1 error generated.
*** Error 1 in /home/swindles/downloads/cfm (Makefile:15 'cfm')
```

**Comment by sophec** [comment]
This is because make is using the CC environment variable to find your C compiler. You don't have it set, so it's falling back to the default, which is `cc`. Set CC to gcc in your environment to fix this. I set CC and CXX in my .profile, though you can just do `make CC=gcc` if you wish.

**Comment by swindlesmccoop** [comment]
For some reason, after setting it to gcc (technically the command is `egcc` but whatever), I'm still getting the same error.
```
[swindles@think420 ~/downloads/cfm]% make CC=egcc
egcc -O2 -pipe  -O3 -s -std=c11 -Wall -W -pedantic  -D_XOPEN_SOURCE=700  cfm.c -o cfm
cfm.c: In function 'main':
cfm.c:1353:19: error: 'SIGWINCH' undeclared (first use in this function); did you mean 'SIGINT'?
 1353 |     if (sigaction(SIGWINCH, &sa_resize, NULL) < 0) {
      |                   ^~~~~~~~
      |                   SIGINT
cfm.c:1353:19: note: each undeclared identifier is reported only once for each function it appears in
cfm.c:1596:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1596 |                 k = '9' + 1;
      |                 ~~^~~~~~~~~
cfm.c:1597:13: note: here
 1597 |             case '1':
      |             ^~~~
*** Error 1 in /home/swindles/downloads/cfm (Makefile:15 'cfm')
```

**Comment by sophec** [comment]
It may be the `_XOPEN_SOURCE` which apparently may limit visibility on BSDs.

**Comment by swindlesmccoop** [comment]
Yeah, that seemed to be it. Thanks. What's it for, anyways?

**Comment by sophec** [comment]
It has the opposite effect on other platforms, enabling features rather than limiting them. Go figure.

**Pull request merged**
